
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Jan 01 13:09:01 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INCREMENT = 38;
  public static final int CONST = 29;
  public static final int NAMESPACE = 42;
  public static final int EQUALS = 37;
  public static final int CONTINUE = 45;
  public static final int GREATER = 41;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int DECREMENT = 39;
  public static final int LESS = 31;
  public static final int FOR = 19;
  public static final int MINUS = 28;
  public static final int STATIC = 20;
  public static final int RPAREN = 7;
  public static final int AND = 30;
  public static final int OR = 46;
  public static final int BOOL = 16;
  public static final int COMMA = 11;
  public static final int CLASS = 43;
  public static final int DIV = 27;
  public static final int PLUS = 10;
  public static final int ASSIGN = 8;
  public static final int IF = 25;
  public static final int DOT = 26;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int NEW = 22;
  public static final int error = 1;
  public static final int MUL = 35;
  public static final int NUMBER = 14;
  public static final int MOD = 34;
  public static final int BREAK = 36;
  public static final int IDENT = 15;
  public static final int VOID = 13;
  public static final int GTE = 23;
  public static final int COLON = 18;
  public static final int LBRACE = 3;
  public static final int ELSE = 24;
  public static final int LSQUARE = 32;
  public static final int NOTEQUALS = 44;
  public static final int RSQUARE = 33;
  public static final int CHARCONST = 17;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 21;
  public static final int PROG = 2;
  public static final int LEQ = 40;
  public static final int PRINT = 12;
}

