
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Sat Dec 23 19:56:20 CET 2023
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int INCREMENT = 39;
  public static final int CONST = 30;
  public static final int NAMESPACE = 43;
  public static final int EQUALS = 38;
  public static final int CONTINUE = 46;
  public static final int GREATER = 42;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int DECREMENT = 40;
  public static final int LESS = 32;
  public static final int FOR = 17;
  public static final int MINUS = 27;
  public static final int STATIC = 18;
  public static final int RPAREN = 7;
  public static final int AND = 31;
  public static final int OR = 47;
  public static final int BOOL = 28;
  public static final int COMMA = 11;
  public static final int CLASS = 44;
  public static final int DIV = 26;
  public static final int PLUS = 10;
  public static final int ASSIGN = 8;
  public static final int IF = 24;
  public static final int DOT = 25;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int NEW = 21;
  public static final int error = 1;
  public static final int MUL = 36;
  public static final int MOD = 35;
  public static final int NUMBER = 14;
  public static final int BREAK = 37;
  public static final int IDENT = 15;
  public static final int VOID = 13;
  public static final int GTE = 22;
  public static final int ARROW = 29;
  public static final int COLON = 16;
  public static final int LBRACE = 3;
  public static final int ELSE = 23;
  public static final int LSQUARE = 33;
  public static final int NOTEQUALS = 45;
  public static final int RSQUARE = 34;
  public static final int CHARCONST = 19;
  public static final int RBRACE = 4;
  public static final int EXTENDS = 20;
  public static final int PROG = 2;
  public static final int LEQ = 41;
  public static final int PRINT = 12;
}

